config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # root "posts#index"

  
  resources :users
  resources :posts
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
belongs_to :user
has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    post = Post.find(params[:original_post])
    @comment = post.comments.build(comment_params)
    @comment.user_id = current_user.id
      if @comment.save
      redirect_to posts_path, notice: "Comment successful"
    else
      redirect_to posts_path, notice: "Comment failed"
    end
  end


private 
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @user = current_user
  end
  
  def index
    @post = Post.new
    # @posts = Post.all
    @comment = Comment.new 
    @comments = Comment.all
  end

  def create
    @post = current_user.posts.build(post_params)
      if @post.save
      redirect_to posts_path, notice: "Post successful"
    else
      render 'new'
    end
  end

  #should be individual post
  def show
    @user = User.find(params[:id])
  end 
  
  def edit
  end

  def update
  end

  def destroy
  end
  
  private

  def post_params 
    params.require(:post).permit(:content)
  end 
  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end 
  
  def index
    @users = User.all 
  end 

  def show
    @post = Post.new
    @posts = Post.all 
    @user = User.find(params[:id])
  end 

  




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to Fakebook</h1>

<%= link_to "Join", new_user_registration_path  %>
<%= link_to 'Log in', new_user_session_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"   %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
      <%# <a class="navbar-brand" href='Fakebook', root_path> %>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Fake Friends", users_path %> </li>
            <li><%= link_to "My Fakebook", new_user_session_path %> </li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "Sign-Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <%else%>
          <ul class="nav navbar-nav navbar-left">
            <li> <%=link_to "Join", new_user_registration_path%></li>
            <li><%=link_to "Log In", new_user_session_path%></li>
          </ul>
        <%end%>
      </nav>


    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %>       
      <%end%>
    </div>
    <%= yield %>   
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input class: "form-control", :content %>
  <%= f.button :submit, class: "btn btn-info" %>
  
<% end %>

app/views/posts/index.html.erb
<h1 class="text-center">Welcome <%= @user.email%></h1>

<h1>Post</h1>
<%= render 'form'%>

<% current_user.posts.reverse.each do |p|%>
  <p class="text-center"><%= p.content %></p>
  <p class="text-center"><%= p.created_at.strftime("%H:%M:%S - %d/%m/%y")%></p>
  
  <% if current_user.id == p.user_id %>
  
    <p class="text-center">
      <%= link_to 'Edit', edit_post_path(p) %> |
      <%= link_to 'Delete', p, method: :delete, data: {confirm: "Are you sure?"} %>
    </p>

  <% p.comments.reverse.each do |c|%>
    <p class="text-center"><%=c.body %></p>
    <p class="text-center"><%= c.created_at.strftime("%H:%M:%S - %d/%m/%y")%></p>

  <%end%>

    <%= simple_form_for @comment do |f| %>
      <%= f.input :body %>
      <%= f.button :submit, class: "btn btn-info" %>
      <%= hidden_field_tag :original_post, p.id%>
    <% end %>


      <% end %>
  <% end %>

app/views/posts/new.html.erb
<h1>Post</h1>
<%= render 'form'%>

app/views/posts/show.html.erb
<% @posts.each do |p|%>
  <p><%=p.content %></p>
  <p><%= p.created_at%></p>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.label :name, 'Your Post', class: "sr-only" %>
  <%= f.input :content, placeholder: "Post something", class: "sr-only" %>
  <%= f.button :submit, class: "btn btn-info" %>
  
<% end %>

app/views/users/index.html.erb
  <% @users.each do |user| %>
    <% if current_user.id != user.id %>
      <li>
        <%= link_to user.email, user %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1 class="text-center">Welcome <%= @user.email%></h1>

<h1>Post</h1>
<%= render 'form'%>

<% @posts.reverse.each do |p|%>
  <p class="text-center"><%=p.content %></p>
  <p class="text-center"><%= p.created_at%></p>
  <p class="text-center">Add comment</p>
<% end %>